# Generated by Django 4.2.4 on 2023-08-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('holder', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
